### PR TITLE
Update to Jenkins 2.89 and others

### PR DESCRIPTION
**Pull request by greg-hellings**
Move default Jenkins to 2.89.4
Update plugin versions to match
Move minimum version of Ansible to 2.4
Eliminate deprecation warnings for newer versions of Ansible
Streamline RPM installation
Bump version to 1.2.0

### CODE REVIEW

**Comment by tehsmyers** [comment]
Any reason to go with 2.89, and not a more recent LTS like 2.121.3?

**Comment by greg-hellings** [comment]
Just to document that we stopped here along the way. The 2.89.4 was used but never got pushed here. I want to get this out the door as 1.2 and immediately turn around with 2.121 and tag 1.3 as soon as this lands.

**Comment by scottlinux** [comment]
Fwiw testing with 2.121.z has been working great for me. Thanks for your help all,

**Comment by abraverm** [comment]
@greg-hellings  please resolve the CI issue:
https://travis-ci.org/RedHatQE/cinch/jobs/426797288#L1529

**Comment by greg-hellings** [comment]
Huh, never seen that code before. Pushing a new changeset that should also update the inspec tests.

**Review by abraverm — APPROVED** [review]

**Pull request merged**
